competition-id: 61da0593-fa9e-11eb-9a38-e5523ddb5e74
Ocp-Apim-Subscription-Key: ff339f2b511144a8aa85dc8892efbd16
cloud-53-login: admin
cloud-53-password: pass01
cloud-53-base-url: 'https://cloud53-dev-apim.azure-api.net/cloud53-dev'
default-ping-count: 5
default-sleep-timer: 3
external-host-ip: 1.1.1.1
exec-timeout: 300
web-53-auth: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjg5Njg1NjcsIm5iZiI6MTYyODkzMjU2Nywic3ViIjoiYWRtaW4ifQ.jOMrxeIQ2doLn5CQvSZOWKCpiMLU5aokpY-wMVKRRTc'

linux-ping-parser: 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"FAIL") }'
distribution-parser: echo $(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//') $(awk '/DISTRIB_RELEASE=/' /etc/*-release | sed 's/DISTRIB_RELEASE=//')
kernel-parser: uname -r
vcpu-count-parser: python3 -c "import os;print(os.cpu_count())"
ram-mb-parser: python3 -c "import os;print(int((os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES')) / 1048576))"
boot-img-parser: cat /proc/cmdline | awk '{print $1}' | awk -F'=' '{print $2}'
python-ver-parser: python3 -c "import platform;print(platform.python_version())"

skip_connections:
  - dummy