#!/bin/bash

export adminuser=azadmin
export password=w%cJ55TbGHxAkYL5
export platform_01_public_ip=20.98.200.22
export platform_02_public_ip=13.77.220.37
export platform_03_public_ip=20.97.71.191
export prefix=gfd-39-comp-01
