#!/bin/bash

export adminuser=azadmin
export password=DvFlrP90dHLc5J=q
export platform_01_public_ip=52.254.20.89
export platform_02_public_ip=52.161.103.71
export platform_03_public_ip=13.66.13.68
export prefix=gfd-39-comp-01
